org = "rust-lang"
name = "cargo"
description = "The Rust package manager"
homepage = "https://doc.rust-lang.org/cargo"
bots = ["rustbot", "rfcbot", "renovate"]

[access.teams]
cargo = "write"
mods = "write"

[[branch-protections]]
pattern = "master"
ci-checks = ["conclusion"]

[[branch-protections]]
pattern = "rust-1.*"
ci-checks = ["conclusion"]
